### ISSUE TITLE
snippets with trailing space have the space removed

### ISSUE THREAD

**Issue by wburningham** [dhoulb/alfred-snippet-generator#1]
I'm trying to create a snippet that will correct a misspelled word and using a space as a delimiter. I try to use the following from my clipboard:

`teh 	the ` (notice the trailling space on both words).

A snippets file is generated, but the keyword has the trailing space, but the snippet is missing a trailing space.

**Comment by dhoulb** [comment]
Just tested this and it seems to work correctly. Pasting TSV content with a space after the keyword or snippet generates a `.alfredsnippets` file with spaces after the keyword and snippet. When I import that file into the latest Alfred (v4) both spaces still exist.

Maybe the place you're copying the TSV content from is stripping the space? I tested Google Sheets and it doesn't seem to strip spaces — but are you maybe using Excel (I don't have Excel to test unfortunately).

**Comment by wburningham** [comment]
You are right. I was texting my auto snippet expansion in a Chrome URL address bar and it looks like it acts weird and removes the trailing space when expanded. All other inputs on a mac work as intended. Seems like an Alfred or Chrome issue for that small case I found.

Thanks for double checking and replying so quickly.
