### ISSUE TITLE
Create tab-separated file from .alfredsnippets file

### ISSUE THREAD

**Issue by gsaslis** [dhoulb/alfred-snippet-generator#2]
Hi @dhoulb 👋 

Thanks for putting this together! 

Any chance you've considered adding the reverse functionality to the generator?
i.e. given a .alfredsnippets file to create the tab-separated file from it? 

This might help folks who are trying to export lists of snippets into other formats (e.g. a `plist` file to be used with [mac text replacements](https://support.apple.com/en-ie/guide/mac-help/mchl2a7bd795/mac))

**Comment by dhoulb** [comment]
Hi @gsaslis — it's a useful idea for sure, but not something I have the capacity for right now.

If I want to personally move away from Alfred in future I'd probably throw something like that together, but for now I'm afraid you'll need to find another way, sorry!

**Comment by dhoulb** [comment]
Though a three-way converter between Alfred, plist, and TSV would be tasty (and potentially TextExpander etc too).
